const defaults={calories:1500,protein:85,carbs:175,fat:50,fibre:25,sugar:35,sodium:2000,water:3};
const key='nutrition-pulse-data-v1';
const state=JSON.parse(localStorage.getItem(key)||'null')||{targets:defaults,water:0.85,foods:[],history:[]};
const fallbackFoods={apple:{calories:52,protein:.3,carbs:13.8,fat:.2,fibre:2.4,sugar:10.4},banana:{calories:89,protein:1.1,carbs:22.8,fat:.3,fibre:2.6,sugar:12.2},almonds:{calories:579,protein:21.2,carbs:21.6,fat:49.9,fibre:12.5,sugar:4.4},mango:{calories:60,protein:.8,carbs:15,fat:.4,fibre:1.6,sugar:13.7},papaya:{calories:43,protein:.5,carbs:10.8,fat:.3,fibre:1.7,sugar:7.8},rice:{calories:130,protein:2.4,carbs:28.2,fat:.3,fibre:.4,sugar:.1},dal:{calories:116,protein:9,carbs:20.1,fat:.4,fibre:7.9,sugar:1.8},roti:{calories:297,protein:11.6,carbs:55.3,fat:2.5,fibre:10.7,sugar:.4},sattu:{calories:400,protein:22,carbs:58,fat:7,fibre:12,sugar:2},'green tea':{calories:1,protein:0,carbs:0,fat:0,fibre:0,sugar:0},'lemon water':{calories:2,protein:0,carbs:.7,fat:0,fibre:0,sugar:.2}};
const $=id=>document.getElementById(id);
const nutrients=['calories','protein','carbs','fat','fibre','sugar'];
const number=value=>Number(value)||0;
const day=new Date().toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'});
let editingIndex=null;
function save(){localStorage.setItem(key,JSON.stringify(state));}
function value(v,unit='g'){return `${Number(v.toFixed(1))}${unit?` ${unit}`:''}`;}
function totals(){return state.foods.reduce((total,food)=>{nutrients.forEach(n=>total[n]+=number(food[n]));return total;},{calories:0,protein:0,carbs:0,fat:0,fibre:0,sugar:0});}
function nutrientField(name){return $(`food${name[0].toUpperCase()}${name.slice(1)}`);}
function setNutrientEditing(enabled){nutrients.forEach(n=>nutrientField(n).readOnly=!enabled);}
function addListItem(list,left,right){const item=document.createElement('li');const a=document.createElement('span');a.textContent=left;const b=document.createElement('strong');b.textContent=right;item.append(a,b);list.appendChild(item);}
function render(){const t=totals();$('today').textContent=day;$('calories').textContent=Math.round(t.calories);$('protein').textContent=value(t.protein);$('water').textContent=value(state.water,'L');$('calorieGoal').textContent=`of ${state.targets.calories.toLocaleString()} kcal`;$('proteinGoal').textContent=`of ${state.targets.protein} g`;$('waterGoal').textContent=`of ${state.targets.water} L`;$('waterBar').style.width=`${Math.min(100,state.water/state.targets.water*100)}%`;$('waterProgress').textContent=`${value(state.water,'L')} of ${state.targets.water} L`;
const list=$('foodList');list.replaceChildren();if(!state.foods.length){addListItem(list,'No food logged yet.','');}else state.foods.forEach((food,index)=>{const item=document.createElement('li');const label=document.createElement('span');label.textContent=`${food.name} · ${value(number(food.protein))} protein`;const actions=document.createElement('span');const calories=document.createElement('strong');calories.textContent=`${Math.round(number(food.calories))} kcal`;const edit=document.createElement('button');edit.type='button';edit.className='secondary';edit.textContent='Edit';edit.addEventListener('click',()=>startEdit(index));actions.append(calories,edit);item.append(label,actions);list.appendChild(item);});
const totalBox=$('totals');totalBox.replaceChildren();[['Calories',`${Math.round(t.calories)} kcal`],['Protein',value(t.protein)],['Carbs',value(t.carbs)],['Fat',value(t.fat)],['Fibre',value(t.fibre)],['Sugar',value(t.sugar)],['Water',value(state.water,'L')]].forEach(([label,amount])=>{const box=document.createElement('div');const caption=document.createElement('span');caption.textContent=label;const amountNode=document.createElement('strong');amountNode.textContent=amount;box.append(caption,amountNode);totalBox.appendChild(box);});
const history=$('historyList');history.replaceChildren();if(!state.history.length){addListItem(history,'Save today to begin your totals-only history.','');}else state.history.forEach(h=>addListItem(history,`${h.date} · P ${value(h.protein)} · C ${value(h.carbs)} · Fat ${value(h.fat)} · Fibre ${value(h.fibre)} · Sugar ${value(h.sugar)}`,`${Math.round(h.calories)} kcal · ${value(h.water,'L')}`));}
function setFoodValues(data){Object.entries(data).forEach(([name,amount])=>nutrientField(name).value=Number(amount.toFixed(1)));}
function nutritionFromProduct(product,quantity){const n=product.nutriments||{};const per100=(...keys)=>keys.map(k=>Number(n[k])).find(Number.isFinite)||0;const factor=quantity/100;return{calories:per100('energy-kcal_100g','energy-kcal')*factor,protein:per100('proteins_100g','proteins')*factor,carbs:per100('carbohydrates_100g','carbohydrates')*factor,fat:per100('fat_100g','fat')*factor,fibre:per100('fiber_100g','fiber')*factor,sugar:per100('sugars_100g','sugars')*factor};}
async function calculateFood(){const name=$('foodName').value.trim();const quantity=number($('foodQuantity').value);const unit=$('foodUnit').value;const status=$('lookupStatus');if(!name||quantity<=0){status.textContent='Enter a food name and quantity first.';return;}setNutrientEditing(false);status.textContent='Finding nutrition values…';const fallback=fallbackFoods[name.toLowerCase()];if(fallback){setFoodValues(Object.fromEntries(nutrients.map(n=>[n,fallback[n]*quantity/100])));status.textContent=`Calculated from the basic food list${unit==='ml'?' (using 1 ml ≈ 1 g).':''}`;return;}try{const endpoint=`https://world.openfoodfacts.org/cgi/search.pl?search_terms=${encodeURIComponent(name)}&search_simple=1&action=process&json=1&page_size=5&fields=product_name,nutriments`;const response=await fetch(endpoint);if(!response.ok)throw new Error();const data=await response.json();const product=(data.products||[]).find(item=>item.nutriments&&Number(item.nutriments['energy-kcal_100g'])>0);if(!product)throw new Error();setFoodValues(nutritionFromProduct(product,quantity));status.textContent=`Calculated from ${product.product_name||'a matching product'}${unit==='ml'?' (using 1 ml ≈ 1 g).':''}. Review values before saving.`;}catch{status.textContent='No match found. Select Enter nutrition manually to type the values.';}}
function resetFoodForm(){const form=$('foodForm');form.reset();$('foodQuantity').value=100;$('foodUnit').value='g';setNutrientEditing(false);editingIndex=null;$('saveFood').textContent='Add to today';$('cancelEdit').hidden=true;$('lookupStatus').textContent='';$('photoNote').textContent='Choose a photo from your album or take a new photo. Confirm nutrition before saving.';}
function startEdit(index){const food=state.foods[index];editingIndex=index;$('foodName').value=food.name;$('foodQuantity').value=food.quantity||100;$('foodUnit').value=food.unit||'g';nutrients.forEach(n=>nutrientField(n).value=number(food[n]));setNutrientEditing(true);$('lookupStatus').textContent='Editing saved entry. Update any nutrition value, then select Update food.';$('saveFood').textContent='Update food';$('cancelEdit').hidden=false;window.scrollTo({top:0,behavior:'smooth'});}
$('addWater').addEventListener('click',()=>{state.water+=.25;save();render();});
$('calculateFood').addEventListener('click',calculateFood);
$('manualNutrition').addEventListener('click',()=>{setNutrientEditing(true);$('lookupStatus').textContent='Enter nutrition values manually, then select Add to today.';});
$('cancelEdit').addEventListener('click',resetFoodForm);
$('foodForm').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;const food={name:form.foodName.value.trim(),quantity:number($('foodQuantity').value),unit:$('foodUnit').value};const hasValues=nutrients.every(n=>{const field=nutrientField(n);food[n]=number(field.value);return field.value!=='';});if(!food.name||food.quantity<=0||!hasValues){$('lookupStatus').textContent='Calculate nutrition or enter the values manually before saving.';return;}if(editingIndex===null)state.foods.push(food);else state.foods[editingIndex]=food;save();resetFoodForm();render();});
$('photo').addEventListener('change',event=>{$('photoNote').textContent=event.target.files.length?'Photo selected from your device. Nutrition suggestions from the photo require a separate AI photo-analysis service.':'Choose a photo from your album or take a new photo. Confirm nutrition before saving.';});
$('showSettings').addEventListener('click',()=>{$('settingsDialog').showModal();const form=$('settingsForm');Object.keys(defaults).forEach(k=>form.elements[k].value=state.targets[k]);});
$('saveTargets').addEventListener('click',event=>{event.preventDefault();const form=$('settingsForm');Object.keys(defaults).forEach(k=>state.targets[k]=number(form.elements[k].value));save();$('settingsDialog').close();render();});
$('saveDay').addEventListener('click',()=>{const t=totals();state.history=state.history.filter(h=>h.date!==day);state.history.unshift({date:day,...t,water:state.water});save();render();});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
