const defaults={calories:1500,protein:85,carbs:175,fat:50,fibre:25,sugar:35,sodium:2000,water:3};
const key='nutrition-pulse-data-v1';
const state=JSON.parse(localStorage.getItem(key)||'null')||{targets:defaults,water:0.85,foods:[],history:[]};
const fallbackFoods={apple:{calories:52,protein:.3,carbs:13.8,fat:.2,fibre:2.4,sugar:10.4},banana:{calories:89,protein:1.1,carbs:22.8,fat:.3,fibre:2.6,sugar:12.2},almonds:{calories:579,protein:21.2,carbs:21.6,fat:49.9,fibre:12.5,sugar:4.4},mango:{calories:60,protein:.8,carbs:15,fat:.4,fibre:1.6,sugar:13.7},papaya:{calories:43,protein:.5,carbs:10.8,fat:.3,fibre:1.7,sugar:7.8},rice:{calories:130,protein:2.4,carbs:28.2,fat:.3,fibre:.4,sugar:.1},dal:{calories:116,protein:9,carbs:20.1,fat:.4,fibre:7.9,sugar:1.8},roti:{calories:297,protein:11.6,carbs:55.3,fat:2.5,fibre:10.7,sugar:.4},sattu:{calories:400,protein:22,carbs:58,fat:7,fibre:12,sugar:2},'green tea':{calories:1,protein:0,carbs:0,fat:0,fibre:0,sugar:0},'lemon water':{calories:2,protein:0,carbs:.7,fat:0,fibre:0,sugar:.2}};
const $=id=>document.getElementById(id);
const number=value=>Number(value)||0;
const day=new Date().toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'});
const nutrients=['calories','protein','carbs','fat','fibre','sugar'];
function save(){localStorage.setItem(key,JSON.stringify(state));}
function totals(){return state.foods.reduce((a,f)=>{nutrients.forEach(n=>a[n]+=f[n]);return a;},{calories:0,protein:0,carbs:0,fat:0,fibre:0,sugar:0});}
function value(v,unit='g'){return `${Number(v.toFixed(1))}${unit?` ${unit}`:''}`;}
function addListItem(list,left,right){const item=document.createElement('li');const leftNode=document.createElement('span');leftNode.textContent=left;const rightNode=document.createElement('strong');rightNode.textContent=right;item.append(leftNode,rightNode);list.appendChild(item);}
function render(){const t=totals();$('today').textContent=day;$('calories').textContent=Math.round(t.calories);$('protein').textContent=value(t.protein);$('water').textContent=value(state.water,'L');$('calorieGoal').textContent=`of ${state.targets.calories.toLocaleString()} kcal`;$('proteinGoal').textContent=`of ${state.targets.protein} g`;$('waterGoal').textContent=`of ${state.targets.water} L`;$('waterBar').style.width=`${Math.min(100,state.water/state.targets.water*100)}%`;$('waterProgress').textContent=`${value(state.water,'L')} of ${state.targets.water} L`;
const list=$('foodList');list.replaceChildren();if(!state.foods.length){addListItem(list,'No food logged yet.','');}else state.foods.forEach(f=>addListItem(list,`${f.name} · ${value(f.protein)} protein`,`${Math.round(f.calories)} kcal`));
const totalBox=$('totals');totalBox.replaceChildren();[['Calories',`${Math.round(t.calories)} kcal`],['Protein',value(t.protein)],['Carbs',value(t.carbs)],['Fat',value(t.fat)],['Fibre',value(t.fibre)],['Sugar',value(t.sugar)],['Water',value(state.water,'L')]].forEach(([label,amount])=>{const box=document.createElement('div');const caption=document.createElement('span');caption.textContent=label;const amountNode=document.createElement('strong');amountNode.textContent=amount;box.append(caption,amountNode);totalBox.appendChild(box);});
const history=$('historyList');history.replaceChildren();if(!state.history.length){addListItem(history,'Save today to begin your totals-only history.','');}else state.history.forEach(h=>addListItem(history,`${h.date} · P ${value(h.protein)} · C ${value(h.carbs)} · Fat ${value(h.fat)} · Fibre ${value(h.fibre)} · Sugar ${value(h.sugar)}`,`${Math.round(h.calories)} kcal · ${value(h.water,'L')}`));}
function setFoodValues(data){Object.entries(data).forEach(([name,amount])=>{$(`food${name[0].toUpperCase()}${name.slice(1)}`).value=Number(amount.toFixed(1));});}
function nutritionFromProduct(product,quantity){const n=product.nutriments||{};const at100=(...keys)=>keys.map(k=>Number(n[k])).find(Number.isFinite)||0;const factor=quantity/100;return{calories:at100('energy-kcal_100g','energy-kcal')*factor,protein:at100('proteins_100g','proteins')*factor,carbs:at100('carbohydrates_100g','carbohydrates')*factor,fat:at100('fat_100g','fat')*factor,fibre:at100('fiber_100g','fiber')*factor,sugar:at100('sugars_100g','sugars')*factor};}
async function calculateFood(){const name=$('foodName').value.trim();const quantity=number($('foodQuantity').value);const status=$('lookupStatus');if(!name||quantity<=0){status.textContent='Enter a food name and quantity first.';return;}status.textContent='Finding nutrition values…';const fallback=fallbackFoods[name.toLowerCase()];if(fallback){setFoodValues(Object.fromEntries(nutrients.map(n=>[n,fallback[n]*quantity/100])));status.textContent='Calculated from the basic food list.';return;}try{const endpoint=`https://world.openfoodfacts.org/cgi/search.pl?search_terms=${encodeURIComponent(name)}&search_simple=1&action=process&json=1&page_size=5&fields=product_name,nutriments`;const response=await fetch(endpoint);if(!response.ok)throw new Error('lookup unavailable');const data=await response.json();const product=(data.products||[]).find(item=>item.nutriments&&Number(item.nutriments['energy-kcal_100g'])>0);if(!product)throw new Error('not found');setFoodValues(nutritionFromProduct(product,quantity));status.textContent=`Calculated from ${product.product_name||'a matching food product'}. Please review before saving.`;}catch{status.textContent='No match found. Try a more specific packaged-food name or use one of the basic foods.';}}
$('addWater').addEventListener('click',()=>{state.water+=.25;save();render();});
$('calculateFood').addEventListener('click',calculateFood);
$('foodForm').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;const food={name:f.foodName.value.trim()};const hasValues=nutrients.every(n=>{const field=$(`food${n[0].toUpperCase()}${n.slice(1)}`);food[n]=number(field.value);return field.value!=='';});if(!food.name||!hasValues||nutrients.some(n=>food[n]<0)){ $('lookupStatus').textContent='Use Calculate nutrition before adding this food.';return;}state.foods.push(food);f.reset();$('foodQuantity').value=100;$('lookupStatus').textContent='';$('photoNote').textContent='Choose a photo from your album or take a new photo. Confirm nutrition before saving.';save();render();});
$('photo').addEventListener('change',e=>{$('photoNote').textContent=e.target.files.length?'Photo selected from your device. Nutrition suggestions from the photo require a separate AI photo-analysis service.':'Choose a photo from your album or take a new photo. Confirm nutrition before saving.';});
$('showSettings').addEventListener('click',()=>{$('settingsDialog').showModal();const f=$('settingsForm');Object.keys(defaults).forEach(k=>f.elements[k].value=state.targets[k]);});
$('saveTargets').addEventListener('click',e=>{e.preventDefault();const f=$('settingsForm');Object.keys(defaults).forEach(k=>state.targets[k]=number(f.elements[k].value));save();$('settingsDialog').close();render();});
$('saveDay').addEventListener('click',()=>{const t=totals();state.history=state.history.filter(h=>h.date!==day);state.history.unshift({date:day,...t,water:state.water});save();render();});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
