import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js';
import {getAuth,onAuthStateChanged,createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import {getFirestore,doc,getDoc,setDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyBx9hA1S2FU-oYkJDnQtivqjnTqJZyg6VA',authDomain:'nutrition-pulse.firebaseapp.com',projectId:'nutrition-pulse',storageBucket:'nutrition-pulse.firebasestorage.app',messagingSenderId:'964919125909',appId:'1:964919125909:web:224636830515588e1f789c'};
const firebaseApp=initializeApp(firebaseConfig);
const auth=getAuth(firebaseApp);
const db=getFirestore(firebaseApp);
let currentUser=null;
let cloudReady=false;
const defaults={calories:1500,protein:85,carbs:175,fat:50,fibre:25,sugar:35,sodium:2000,water:3};
const dayKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const displayDate=dateKey=>new Date(`${dateKey}T00:00:00`).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'});
const key='nutrition-pulse-data-v1';
const backupKey='nutrition-pulse-backup-v1';
const savedText=localStorage.getItem(key)||localStorage.getItem(backupKey);
const state=JSON.parse(savedText||'null')||{targets:defaults,water:0,foods:[],history:[]};
state.currentDate=state.currentDate||dayKey();
state.customFoods=state.customFoods||{};
const fallbackFoods={apple:{calories:52,protein:.3,carbs:13.8,fat:.2,fibre:2.4,sugar:10.4},banana:{calories:89,protein:1.1,carbs:22.8,fat:.3,fibre:2.6,sugar:12.2},almonds:{calories:579,protein:21.2,carbs:21.6,fat:49.9,fibre:12.5,sugar:4.4},mango:{calories:60,protein:.8,carbs:15,fat:.4,fibre:1.6,sugar:13.7},papaya:{calories:43,protein:.5,carbs:10.8,fat:.3,fibre:1.7,sugar:7.8},rice:{calories:130,protein:2.4,carbs:28.2,fat:.3,fibre:.4,sugar:.1},dal:{calories:116,protein:9,carbs:20.1,fat:.4,fibre:7.9,sugar:1.8},roti:{calories:297,protein:11.6,carbs:55.3,fat:2.5,fibre:10.7,sugar:.4},sattu:{calories:400,protein:22,carbs:58,fat:7,fibre:12,sugar:2},'green tea':{calories:1,protein:0,carbs:0,fat:0,fibre:0,sugar:0},'lemon water':{calories:2,protein:0,carbs:.7,fat:0,fibre:0,sugar:.2}};
const pieceWeights={apple:182,banana:118,almonds:1.2,mango:200,papaya:140,roti:40};
const foodKey=name=>name.trim().toLowerCase().replace(/\s+/g,' ');
function comparableQuantity(name,quantity,unit){return unit==='pieces'&&pieceWeights[foodKey(name)]?quantity*pieceWeights[foodKey(name)]:quantity;}
const $=id=>document.getElementById(id);
const nutrients=['calories','protein','carbs','fat','fibre','sugar'];
const number=value=>Number(value)||0;
let editingIndex=null;
let manualMode=false;
function openBackupDb(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window)){reject(new Error('Unavailable'));return;}const request=indexedDB.open('nutrition-pulse-backups',1);request.onupgradeneeded=()=>request.result.createObjectStore('data');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function saveIndexedBackup(){try{const db=await openBackupDb();const transaction=db.transaction('data','readwrite');transaction.objectStore('data').put(JSON.parse(JSON.stringify(state)),'latest');}catch{}}
async function recoverIndexedBackup(){if(savedText)return;try{const db=await openBackupDb();const transaction=db.transaction('data','readonly');const request=transaction.objectStore('data').get('latest');request.onsuccess=()=>{const recovered=request.result;if(recovered&&Array.isArray(recovered.foods)){Object.assign(state,recovered);save();render();}};}catch{}}
function freshState(){return{targets:{...defaults},water:0,foods:[],history:[],currentDate:dayKey(),customFoods:{}};}
function replaceState(data){Object.keys(state).forEach(name=>delete state[name]);Object.assign(state,freshState(),data||{});state.currentDate=state.currentDate||dayKey();state.customFoods=state.customFoods||{};state.foods=state.foods||[];state.history=state.history||[];}
const userCacheKey=uid=>`${key}-${uid}`;
async function saveCloud(){if(!cloudReady||!currentUser)return;try{await setDoc(doc(db,'users',currentUser.uid,'private','appData'),{state:JSON.parse(JSON.stringify(state)),updatedAt:serverTimestamp()});}catch(error){console.warn('Cloud save failed',error);}}
function save(){const data=JSON.stringify(state);localStorage.setItem(key,data);localStorage.setItem(backupKey,data);if(currentUser)localStorage.setItem(userCacheKey(currentUser.uid),data);saveIndexedBackup();saveCloud();}
async function loadUserState(user){cloudReady=false;const userDoc=doc(db,'users',user.uid,'private','appData');try{const snapshot=await getDoc(userDoc);if(snapshot.exists()){replaceState(snapshot.data().state);}else{const cached=localStorage.getItem(userCacheKey(user.uid));if(cached)replaceState(JSON.parse(cached));else if(!localStorage.getItem('nutrition-pulse-legacy-migrated')){localStorage.setItem('nutrition-pulse-legacy-migrated','true');}else replaceState(freshState());}cloudReady=true;save();render();}catch(error){replaceState(freshState());cloudReady=false;render();$('authMessage').textContent='Could not load cloud data. Please check your internet connection.';}}
function value(v,unit='g'){return `${Number(v.toFixed(1))}${unit?` ${unit}`:''}`;}
function totals(){return state.foods.reduce((total,food)=>{nutrients.forEach(n=>total[n]+=number(food[n]));return total;},{calories:0,protein:0,carbs:0,fat:0,fibre:0,sugar:0});}
function waterMl(){return Math.round(number(state.water)*1000/50)*50;}
function archiveCurrentDay(){const t=totals();if(!state.foods.length&&waterMl()===0)return;const id=state.currentDate;state.history=state.history.filter(h=>(h.id||h.date)!==id);state.history.unshift({id,date:displayDate(id),...t,water:waterMl()/1000});}
function ensureCurrentDay(){const today=dayKey();if(state.currentDate===today)return false;archiveCurrentDay();state.currentDate=today;state.foods=[];state.water=0;editingIndex=null;save();return true;}
const keyFromDate=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
function historyKey(record){if(record.id)return record.id;const parsed=new Date(record.date);return Number.isNaN(parsed.getTime())?'':keyFromDate(parsed);}
function weeklyData(todayTotals){const current=new Date(`${state.currentDate}T00:00:00`);const weekday=(current.getDay()+6)%7;const start=new Date(current);start.setDate(current.getDate()-weekday);const end=new Date(start);end.setDate(start.getDate()+6);const startKey=keyFromDate(start);const endKey=keyFromDate(end);const weekly={calories:0,protein:0,carbs:0,fat:0,fibre:0,sugar:0,water:0};state.history.filter(h=>{const id=historyKey(h);return id&&id>=startKey&&id<=endKey&&id!==state.currentDate;}).forEach(h=>{nutrients.forEach(n=>weekly[n]+=number(h[n]));weekly.water+=number(h.water);});nutrients.forEach(n=>weekly[n]+=number(todayTotals[n]));weekly.water+=waterMl()/1000;return{weekly,start,end};}
function renderWeekly(todayTotals){const data=weeklyData(todayTotals);const weekStart=displayDate(keyFromDate(data.start));const weekEnd=displayDate(keyFromDate(data.end));$('weekRange').textContent=`${weekStart} – ${weekEnd}`;const rows=[['Calories','calories','kcal'],['Protein','protein','g'],['Carbs','carbs','g'],['Fat','fat','g'],['Fibre','fibre','g'],['Sugar','sugar','g'],['Water','water','ml']];const body=$('weeklySummary');body.replaceChildren();rows.forEach(([label,keyName,unit])=>{const target=number(state.targets[keyName])*7*(unit==='ml'?1000:1);const achieved=data.weekly[keyName]*(unit==='ml'?1000:1);const remaining=Math.max(0,target-achieved);const over=achieved>target;const row=document.createElement('tr');[label,`${Math.round(target).toLocaleString()} ${unit}`,`${Math.round(achieved).toLocaleString()} ${unit}`,`${Math.round(remaining).toLocaleString()} ${unit}`].forEach(text=>{const cell=document.createElement('td');cell.textContent=text;row.appendChild(cell);});const status=document.createElement('td');status.textContent=over?`Over by ${Math.round(achieved-target).toLocaleString()} ${unit}`:'Within limit';status.style.color=over?'#dc2626':'#15803d';status.style.fontWeight='700';row.appendChild(status);body.appendChild(row);});const calorieTarget=Math.max(1,number(state.targets.calories)*7);const proteinTarget=Math.max(1,number(state.targets.protein)*7);const caloriePercent=Math.min(100,Math.round(data.weekly.calories/calorieTarget*100));const proteinPercent=Math.min(100,Math.round(data.weekly.protein/proteinTarget*100));$('weeklyCalorieDonut').style.setProperty('--progress',`${caloriePercent}%`);$('weeklyProteinDonut').style.setProperty('--progress',`${proteinPercent}%`);$('weeklyCalorieValue').textContent=`${caloriePercent}%`;$('weeklyProteinValue').textContent=`${proteinPercent}%`;$('weeklyCalorieDonut').setAttribute('aria-label',`Weekly calories: ${Math.round(data.weekly.calories)} of ${calorieTarget} kcal`);$('weeklyProteinDonut').setAttribute('aria-label',`Weekly protein: ${data.weekly.protein.toFixed(1)} of ${proteinTarget} g`);}
function nutrientField(name){return $(`food${name[0].toUpperCase()}${name.slice(1)}`);}
function setNutrientEditing(enabled){nutrients.forEach(n=>nutrientField(n).readOnly=!enabled);}
function addListItem(list,left,right){const item=document.createElement('li');const a=document.createElement('span');a.textContent=left;const b=document.createElement('strong');b.textContent=right;item.append(a,b);list.appendChild(item);}
function render(){ensureCurrentDay();const t=totals();const currentWaterMl=waterMl();const waterTargetMl=Math.max(50,number(state.targets.water)*1000);$('today').textContent=displayDate(state.currentDate);$('calories').textContent=Math.round(t.calories);$('protein').textContent=value(t.protein);$('water').textContent=`${currentWaterMl} ml`;$('calorieGoal').textContent=`of ${state.targets.calories.toLocaleString()} kcal`;$('proteinGoal').textContent=`of ${state.targets.protein} g`;$('waterGoal').textContent=`of ${waterTargetMl.toLocaleString()} ml`;$('waterBar').style.width=`${Math.min(100,currentWaterMl/waterTargetMl*100)}%`;$('waterProgress').textContent=`${currentWaterMl.toLocaleString()} of ${waterTargetMl.toLocaleString()} ml`;const calorieTarget=Math.max(1,number(state.targets.calories));const proteinTarget=Math.max(1,number(state.targets.protein));const caloriePercent=Math.min(100,Math.round(t.calories/calorieTarget*100));const proteinPercent=Math.min(100,Math.round(t.protein/proteinTarget*100));$('calorieDonut').style.setProperty('--progress',`${caloriePercent}%`);$('proteinDonut').style.setProperty('--progress',`${proteinPercent}%`);$('calorieChartValue').textContent=`${caloriePercent}%`;$('proteinChartValue').textContent=`${proteinPercent}%`;$('calorieDonut').setAttribute('aria-label',`Calories: ${Math.round(t.calories)} of ${calorieTarget} kcal, ${caloriePercent}%`);$('proteinDonut').setAttribute('aria-label',`Protein: ${t.protein.toFixed(1)} of ${proteinTarget} g, ${proteinPercent}%`);
const list=$('foodList');list.replaceChildren();if(!state.foods.length){const row=document.createElement('tr');const cell=document.createElement('td');cell.colSpan=5;cell.className='empty';cell.textContent='No food logged yet.';row.appendChild(cell);list.appendChild(row);}else state.foods.forEach((food,index)=>{const row=document.createElement('tr');const cells=[food.name,`${food.quantity||''} ${food.unit||''}`.trim(),value(number(food.protein)),`${Math.round(number(food.calories))} kcal`];cells.forEach(text=>{const cell=document.createElement('td');cell.textContent=text;row.appendChild(cell);});const action=document.createElement('td');const edit=document.createElement('button');edit.type='button';edit.className='secondary';edit.textContent='Edit';edit.addEventListener('click',()=>startEdit(index));action.appendChild(edit);row.appendChild(action);list.appendChild(row);});
const totalBox=$('totals');totalBox.replaceChildren();[['Calories',`${Math.round(t.calories)} kcal`],['Protein',value(t.protein)],['Carbs',value(t.carbs)],['Fat',value(t.fat)],['Fibre',value(t.fibre)],['Sugar',value(t.sugar)],['Water',`${currentWaterMl} ml`]].forEach(([label,amount])=>{const box=document.createElement('div');const caption=document.createElement('span');caption.textContent=label;const amountNode=document.createElement('strong');amountNode.textContent=amount;box.append(caption,amountNode);totalBox.appendChild(box);});
const history=$('historyList');history.replaceChildren();if(!state.history.length){const row=document.createElement('tr');const cell=document.createElement('td');cell.colSpan=8;cell.className='empty';cell.textContent='Completed days will appear here automatically.';row.appendChild(cell);history.appendChild(row);}else state.history.forEach(h=>{const row=document.createElement('tr');[h.date,`${Math.round(number(h.calories))} kcal`,value(number(h.protein)),value(number(h.carbs)),value(number(h.fat)),value(number(h.fibre)),value(number(h.sugar)),`${Math.round(number(h.water)*1000/50)*50} ml`].forEach(text=>{const cell=document.createElement('td');cell.textContent=text;row.appendChild(cell);});history.appendChild(row);});renderWeekly(t);}
function setFoodValues(data){nutrients.forEach(name=>{const amount=data[name];nutrientField(name).value=amount===null||amount===undefined?'':Number(number(amount).toFixed(1));});}
function nutritionFromProduct(product,quantity){const n=product.nutriments||{};const per100=(...keys)=>keys.map(k=>Number(n[k])).find(Number.isFinite)||0;const factor=quantity/100;return{calories:per100('energy-kcal_100g','energy-kcal')*factor,protein:per100('proteins_100g','proteins')*factor,carbs:per100('carbohydrates_100g','carbohydrates')*factor,fat:per100('fat_100g','fat')*factor,fibre:per100('fiber_100g','fiber')*factor,sugar:per100('sugars_100g','sugars')*factor};}
async function calculateFood(){const name=$('foodName').value.trim();const quantity=number($('foodQuantity').value);const unit=$('foodUnit').value;const status=$('lookupStatus');if(!name||quantity<=0){status.textContent='Enter a food name and quantity first.';return;}manualMode=false;setNutrientEditing(false);const keyName=foodKey(name);const fallback=fallbackFoods[keyName];const quantityInGrams=comparableQuantity(name,quantity,unit);const savedFood=state.customFoods[keyName];const compatibleSavedFood=savedFood&&(savedFood.baseUnit===unit||(savedFood.baseUnit!=='pieces'&&unit!=='pieces')||Boolean(pieceWeights[keyName]));if(compatibleSavedFood&&savedFood.baseQuantity>0){const factor=quantityInGrams/savedFood.baseQuantity;setFoodValues(Object.fromEntries(nutrients.map(n=>[n,savedFood[n]===null?null:number(savedFood[n])*factor])));manualMode=true;setNutrientEditing(true);status.textContent=`Calculated from your saved manual values for ${savedFood.name}. Please review and save.`;return;}if(unit==='pieces'&&!pieceWeights[keyName]){status.textContent='No saved manual values were found for this food. For new foods in pieces, use grams or enter nutrition manually.';return;}status.textContent='Finding nutrition values…';if(fallback){setFoodValues(Object.fromEntries(nutrients.map(n=>[n,fallback[n]*quantityInGrams/100])));status.textContent=`Calculated from the basic food list${unit==='ml'?' (using 1 ml ≈ 1 g).':unit==='pieces'?` (using ~${pieceWeights[keyName]} g per piece).`:''}`;return;}try{const endpoint=`https://world.openfoodfacts.org/cgi/search.pl?search_terms=${encodeURIComponent(name)}&search_simple=1&action=process&json=1&page_size=5&fields=product_name,nutriments`;const response=await fetch(endpoint);if(!response.ok)throw new Error();const data=await response.json();const product=(data.products||[]).find(item=>item.nutriments&&Number(item.nutriments['energy-kcal_100g'])>0);if(!product)throw new Error();setFoodValues(nutritionFromProduct(product,quantityInGrams));status.textContent=`Calculated from ${product.product_name||'a matching product'}${unit==='ml'?' (using 1 ml ≈ 1 g).':''}. Review values before saving.`;}catch{status.textContent='No match found. Select Enter nutrition manually to type the values.';}}
function resetFoodForm(){const form=$('foodForm');form.reset();$('foodQuantity').value=100;$('foodUnit').value='g';manualMode=false;setNutrientEditing(false);editingIndex=null;$('saveFood').textContent='Add to today';$('cancelEdit').hidden=true;$('lookupStatus').textContent='';$('photoNote').textContent='Choose a photo from your album or take a new photo. Confirm nutrition before saving.';}
function startEdit(index){const food=state.foods[index];editingIndex=index;manualMode=true;$('foodName').value=food.name;$('foodQuantity').value=food.quantity||100;$('foodUnit').value=food.unit||'g';nutrients.forEach(n=>nutrientField(n).value=food[n]??'');setNutrientEditing(true);$('lookupStatus').textContent='Editing saved entry. Unknown nutrient values may stay blank; blanks are not included in totals.';$('saveFood').textContent='Update food';$('cancelEdit').hidden=false;window.scrollTo({top:0,behavior:'smooth'});}
$('addWater').addEventListener('click',()=>{state.water=(waterMl()+50)/1000;save();render();});
$('calculateFood').addEventListener('click',calculateFood);
$('manualNutrition').addEventListener('click',()=>{manualMode=true;setNutrientEditing(true);$('lookupStatus').textContent='Enter known nutrition values manually. Leave unknown values blank; blanks are not included in totals.';});
$('cancelEdit').addEventListener('click',resetFoodForm);
$('foodForm').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;const food={name:form.foodName.value.trim(),quantity:number($('foodQuantity').value),unit:$('foodUnit').value};const hasValues=nutrients.every(n=>{const field=nutrientField(n);food[n]=field.value===''?null:number(field.value);return field.value!=='';});if(!food.name||food.quantity<=0||(!manualMode&&!hasValues)){$('lookupStatus').textContent='Calculate nutrition or use Enter nutrition manually before saving.';return;}if(manualMode){const baseQuantity=comparableQuantity(food.name,food.quantity,food.unit);state.customFoods[foodKey(food.name)]={name:food.name,baseQuantity,baseUnit:food.unit,...Object.fromEntries(nutrients.map(n=>[n,food[n]]))};}if(editingIndex===null)state.foods.push(food);else state.foods[editingIndex]=food;save();resetFoodForm();render();});
$('photo').addEventListener('change',event=>{$('photoNote').textContent=event.target.files.length?'Photo selected from your device. Nutrition suggestions from the photo require a separate AI photo-analysis service.':'Choose a photo from your album or take a new photo. Confirm nutrition before saving.';});
$('downloadBackup').addEventListener('click',()=>{const file=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(file);link.download=`nutrition-pulse-backup-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(link.href);});
$('restoreBackup').addEventListener('click',()=>$('restoreFile').click());
$('restoreFile').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{const recovered=JSON.parse(await file.text());if(!Array.isArray(recovered.foods)||!recovered.targets)throw new Error();if(!confirm('Replace the current entries with this backup?'))return;Object.assign(state,recovered);save();render();alert('Your backup has been restored.');}catch{alert('This backup file could not be read. Please choose a Nutrition Pulse backup file.');}finally{event.target.value='';}});
$('showSettings').addEventListener('click',()=>{$('settingsDialog').showModal();const form=$('settingsForm');Object.keys(defaults).forEach(k=>form.elements[k].value=state.targets[k]);});
$('saveTargets').addEventListener('click',event=>{event.preventDefault();const form=$('settingsForm');Object.keys(defaults).forEach(k=>state.targets[k]=number(form.elements[k].value));save();$('settingsDialog').close();render();});
$('saveDay').addEventListener('click',()=>{ensureCurrentDay();archiveCurrentDay();save();render();});
function scheduleMidnightCheck(){const now=new Date();const midnight=new Date(now.getFullYear(),now.getMonth(),now.getDate()+1);setTimeout(()=>{if(currentUser)render();scheduleMidnightCheck();},midnight-now+1000);}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&currentUser)render();});
$('authForm').addEventListener('submit',async event=>{event.preventDefault();const email=$('authEmail').value.trim();const password=$('authPassword').value;$('authMessage').textContent='Signing in…';try{await signInWithEmailAndPassword(auth,email,password);$('authMessage').textContent='';}catch(error){$('authMessage').textContent=error.message.replace('Firebase: ','');}});
$('signupButton').addEventListener('click',async()=>{const email=$('authEmail').value.trim();const password=$('authPassword').value;if(!email||!password){$('authMessage').textContent='Enter your email address and password first.';return;}$('authMessage').textContent='Creating account…';try{await createUserWithEmailAndPassword(auth,email,password);$('authMessage').textContent='';}catch(error){$('authMessage').textContent=error.message.replace('Firebase: ','');}});
$('signOutButton').addEventListener('click',()=>signOut(auth));
onAuthStateChanged(auth,async user=>{currentUser=user;if(!user){cloudReady=false;$('mainApp').hidden=true;$('authScreen').hidden=false;$('authPassword').value='';return;}$('authScreen').hidden=true;$('mainApp').hidden=false;$('userEmail').textContent=user.email||'';await loadUserState(user);});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');scheduleMidnightCheck();
